fix: excepción parseInt sobre el año del modelo
Ahora mismo, lo que impide ejecutar el test es esta excepción:

entry: {"Eléctrico":"Mii electric Ficha Tecnica","Potencia":"83 hp / 61 kW","Año":"2019"}
Is Año fetched null?false
entry.get('Año') -> "2019", which type is 2019
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.563 s <<< FAILURE! -- in es.ual.dra.autodiagnostico.service.core.DataPopulationServiceIntegrationTest
[ERROR] es.ual.dra.autodiagnostico.service.core.DataPopulationServiceIntegrationTest.testPopulateFromJson -- Time elapsed: 0.688 s <<< ERROR!
java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "<local6>" is null
	at es.ual.dra.autodiagnostico.service.core.DataPopulationService.computeATScore(DataPopulationService.java:202)
	at es.ual.dra.autodiagnostico.service.core.DataPopulationService.lambda$processTableVersions$5(DataPopulationService.java:152)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at es.ual.dra.autodiagnostico.service.core.DataPopulationService.processTableVersions(DataPopulationService.java:136)
	at es.ual.dra.autodiagnostico.service.core.DataPopulationService.processModel(DataPopulationService.java:93)
	at es.ual.dra.autodiagnostico.service.core.DataPopulationService.populateFromFile(DataPopulationService.java:77)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:359)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:380)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:728)
	at es.ual.dra.autodiagnostico.service.core.DataPopulationService$$SpringCGLIB$$0.populateFromFile(<generated>)
	at es.ual.dra.autodiagnostico.service.core.DataPopulationServiceIntegrationTest.testPopulateFromJson(DataPopulationServiceIntegrationTest.java:42)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)